name: Daily API Backup

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'  # Todos los días a la 1:00 AM (UTC)

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
      - name: Obtener datos de la API con curl
        run: curl -X GET https://movimientos-del-alma-backend-develop.up.railway.app/users/getAllStudents -o users.json

      - name: Convertir JSON a SQL
        run: |
          jq -r '.response[] | "INSERT INTO students (id, identification_number, name, lastname, email, nationality) VALUES (\'\(.id)\', \'\(.identification_number)\', \'\(.name)\', \'\(.lastname)\', \'\(.email)\', \'\(.nationality)\');"' users.json > backup_users_$(date +%Y%m%d%H%M%S).sql

      - name: Crear carpeta para el backup
        run: |
          mkdir -p backup
          mv * backup/

      - name: Subir el backup como artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-database-backup
=======
      - name: Definir TIMESTAMP en UTC-3 con formato legible
        run: echo "TIMESTAMP=$(date -u --date='3 hours ago' +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Verificar TIMESTAMP
        run: echo "El timestamp es ${TIMESTAMP}"

      - name: Obtener datos de la API con curl
        run: curl -X GET https://movimientos-del-alma-backend-develop.up.railway.app/users/getAllStudents -o backup_users_${TIMESTAMP}.json

      - name: Convertir JSON a SQL
        run: |
          jq -r '.response[] | "INSERT INTO students (id, identification_number, name, lastname, email, nationality) VALUES (''\(.id)'', ''\(.identification_number)'', ''\(.name)'', ''\(.lastname)'', ''\(.email)'', ''\(.nationality)'');"' backup_users_${TIMESTAMP}.json > backup_users_${TIMESTAMP}.sql
     
      - name: Crear carpeta para el backup
        run: |
          mkdir -p backup
          mv backup_users_${TIMESTAMP}.json backup/
          mv backup_users_${TIMESTAMP}.sql backup/
          
      - name: Subir el backup como artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-database-backup-${{ env.TIMESTAMP }}
>>>>>>> cca7fba3af6e3fdd12f270016f2fc761cee90c33
          path: backup/
